### ISSUE TITLE
boringyuri-dagger fails incremental compilation sometimes

### ISSUE THREAD

**Issue by bomiyr** [anton-novikau/boringYURI#26]
Annotation processors execution order not specified and can be especially tricky during incremental build. Sometimes build fails with:
```
error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process *my.package*.BoringYuriModule because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
```

So I think boringyuri-dagger MUST be executed only after main boringyuri processor. Maybe it can be achieved by creating `@BoringYuriGenerated` annotation and adding it to all generated files. In this case boringyuri-dagger can listen for this annotation and generate dagger module when all dependencies could be resolved.

**Comment by anton-novikau** [comment]
Hey @bomiyr! Good catch! Thanks for reporting this issue and for the idea how to fix it.

Could you let me know how important this one is to you because the fix and release a new build could probably take a couple of weeks for me. Would it work for you? Otherwise you're very welcome to submit a PR. As soon as the PR is approved I can make a release of the new version the very same day.

**Comment by bomiyr** [comment]
It is not sow important, we disabled `boringyuri-dagger` for now... As we also had other problems with incremental code generation for Dagger, we decided to minimize such cases.

**Comment by anton-novikau** [comment]
@bomiyr please check if the version `1.2.1` helps with the incremental processing issue in your project configuration. I used a little different approach from what you've suggested, but it this one also waits until all the `UriFactory` implementations are compiled and only then it generates a dagger module for them. Please let me know if the fix helps or now.
